# Generated by Django 3.2 on 2021-07-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.IntegerField(choices=[(1, 'waste of time'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Loved  it')]),
        ),
    ]
